# Conclusion

<!--
Discuss: main takeaways of your exploration, limitations, future directions, lessons learned.

(suggested: 1 page)
-->
Our deep dive into CDC data from 1999 to 2000 has clarified a central question: **Alzheimer’s disease**, **suicide**, and **unintentional injuries** have had the most dramatic percentage increase in the last two decades. Amazingly, many causes of death, such as cancer and heart disease, stroke, influenza, and CLRD have been on the decline. 

There is a notable **correlation between rising life expectancy and the increase in Alzheimer’s disease**. Today, a larger portion of the population is likely to reach the age where the risk of Alzheimer’s disease is significantly higher. In particular, 60 years old and above is the period where the likelihood of Alzheimer’s disease becomes elevated. Furthermore, **according to the CDC, Black people are almost twice as likely to develop Alzheimer’s disease**. The rising mortality rates have been observed particularly in several southern states, including **Mississippi, Alabama, and Louisiana**, which have a significant black population proportion.

There is **a link between high opioid dispensing rates and unintentional injury deaths**. The states that had the highest average opioid dispensing rates and the states that had the highest average death rates had a significant overlap — in particular, **West Virginia, Tennessee, Kentucky, Oklahoma, and Mississippi**. The opioid epidemic has had several waves of mortalities in the last decade. Our visualization across the entire United States showed that the **most devastating of these waves occurred after 2013 coinciding with fentanyl trafficking**. After this point, the death rate has been soaring ever since. The opioid epidemic looks like an unfortunate intersection of increased medical dispensing colliding with fentanyl trafficking. It’s possible that patients developed addictions via medical prescriptions and to satisfy their addictions later, some patients could have turned to street drugs. Fentanyl has proved to be extremely potent and deadly. 

Also, we wanted to find a correlation that seemed a bit surprising. One striking observation was the **strong negative correlation between population density and suicide**. Though the pattern seems a bit surprising, it shines a light on **geographical isolation, which can exacerbate loneliness**. According to the CDC, loneliness is associated with higher rates of depression, anxiety, and suicide. This relationship between geographical isolation and loneliness is quantitatively expressed via population density regression analysis.

In summary, the project revealed some remarkable patterns, nuances, and trends.
