# Interactive graph

Instructions: select one of the top 3 causes of death in the United States from the options menu.

-   The first map (i.e. map with bubbles) shows which states have the highest age-adjusted death rate (expressed as the value per 100,000 people). Thus, a bigger bubble corresponds to a higher rate.

-   The second map (i.e. heatmap) shows which states have seen the most significant increase expressed as a percentage change from 1999 to 2020. The more red the state is colored, the higher the increase is. 

Hence, we can examine two metrics simultaneously: age-adjusted death rate in the first map and percentage change in the second map.

<!--
    -   If in 1999 1 person was dying from Cancer and in 2020 2 were dying because of Cancer, then the growth has been 100% in the death rate.
-->
*For example: consider choosing Alzheimer's Disease and focusing on Mississippi. The bubble map shows that Mississippi has had the highest age-adjusted death rate due to Alzheimer's in the United States: 58 deaths per 100,000 people in 2020. Moreover, not only does it have the highest death rate, but it has seen the largest growth since 1999 in this metric: a 336% increase.*
<!--
-   Although not visible in this interactive chart, we provided an explanaition in the results section: race could explain the differences.
-->

```{=html}
<style>
  * {
    font-family: sans-serif;
  }
</style>
```
::: {#slicer}
:::

::: {#plot style="width: 800; height: 500px;"}
:::

::: {#plot2 style="width: 800px; height: 500px;"}
:::

```{=html}
<script src="plotly-2.27.0.min.js""></script>
<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
```
```{=html}
<script src="scripts/myscript.js"></script>
```
Source:

<https://plotly.com/javascript/bubble-maps/>

<https://plotly.com/javascript/choropleth-maps/>
