# Introduction

Explain why you chose this topic, and the questions you are interested in studying. Provide context for readers who are not familiar with the topic.

(suggested: 1 page)






The CDC is a national public health institute in the United States, dedicated to protecting health and promoting quality of life through the prevention and control of disease, injury, and disability. The CDC provides free access to a wealth of public health data and resources.


Specifically, we are going to work with the ICD-10 113 Cause List, which holds significant importance within the framework of the International Classification of Diseases. In particular this is the 10th Revision (ICD-10), which is widely acknowledged as a universally accepted standard for the systematic classification of health conditions and the determination of causes of mortality.


___

The comprehensive data on causes of death is provided by the CDC. It includes crude and age-adjusted rates and death tolls by state, race, and year, and serves as a solid foundation for addressing our research questions. 

First, we will identify the top 10 highest causes of death historically over the last two decades. Then, we will address a more interesting question. We will distinguish which causes of death whose rates appear to be steady and identify the causes of death that appear to be aggressively increasing. In several instances, we anticipate that this will require us to compare time series and choose adequate metrics in order to appropriately make such comparisons. Conveniently, the age-adjusted death rate gives us an accurate glimpse while taking into account the distribution of the age groups in the US. 

A particularly interesting question that we want to answer is to identify which causes have had the fastest rate of growth in terms of age-adjusted death rate. For example, a potent question to answer would be the following: have certain causes of death been on the increase or on the decrease in the last two decades? If so, are there any outliers among them, especially if we break down geographically by state? This would require careful analysis of percentage change year-by-year and analyzing the data by state. Intuitively, we are aware that certain causes of death will show up in our research (one specific example that we anticipate seeing is the deaths due to the opioid epidemic, which has been ongoing for almost a decade now). Indubitably, we expect to find surprising results. 

The research plan depends on exploring the causes of death on a state-by-state basis. This will uncover states with disproportionately high death rates from specific causes, highlighting regions where healthcare investment may be urgently needed. It will be remarkably informative to see which states fare well with certain rising causes of death, and which states are exhibiting alarming rates in comparison to others. Identifying such trends can help policymakers and professionals (e.g., doctors, nurses, mental health professionals, representatives) have a clearer understanding of the reasons behind the spikes in deaths and hopefully help guide them towards adequate solutions to mitigate the quickly rising causes of death.
