# Results

```{r}
library(dplyr)
library(readr)
library(dplyr)
library(forcats)
library(ggplot2)

lead_cod_2 = read_csv("NCHS_-_Leading_Causes_of_Death__United_States.csv")

# BY STATE
lead_cod_2_by_state = lead_cod_2 %>% filter(State != "United States")
# lead_cod_2_by_state

# LOOKING AT USA
lead_cod_2_USA = lead_cod_2 %>% filter(State == "United States")
#lead_cod_2_USA

# FILTER FOR 2008-2017
lead_cod_2_USA_from_2008 = lead_cod_2_USA %>% filter(Year >= 2008)
lead_cod_2_by_state_from_2008 = lead_cod_2_by_state %>% filter(Year >= 2008)
```

```{r}
####################################################

"Total Aggregate Deaths by Cause from 2008 through 2017"
# Group to do a factor reorder
lead_cod_2_USA_from_2008_mod <- lead_cod_2_USA %>% 
  filter(Year >= 2008) %>%
  mutate(`Cause Name` = as.factor(`Cause Name`)) %>% # Ensure 'Cause Name' is a factor
  group_by(`Cause Name`) %>%
  summarise(Total_Deaths = sum(Deaths, na.rm = TRUE)) %>%
  mutate(`Cause Name` = fct_reorder(`Cause Name`, Total_Deaths, .desc=TRUE)) %>%
  ungroup()

# Now create the ggplot
ggplot(lead_cod_2_USA_from_2008_mod, aes(x = `Cause Name`, y = Total_Deaths)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cause Name", y = "Total Deaths", title = "Total Aggregate Deaths by Cause from 2008 through 2017")

###################################################
```

```{r}
###################################################
# DEATHS INCREASING OVER THE YEARS
yearly_data <- lead_cod_2_USA %>%
  group_by(Year) %>%
  summarise(Total_Deaths = sum(Deaths, na.rm = TRUE))

# Create a bar chart
ggplot(yearly_data, aes(x = Year, y = Total_Deaths)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_continuous(breaks = 2008:max(yearly_data$Year), limits = c(2007, 2018)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Year", y = "Total Deaths", title = "Total Deaths per Year from 2008 Onwards")



######################################################


```


```{r}
"Total Deaths by Cause and Year from 2008-2017 Broken Down By Year"
lead_cod_2_USA_from_2008_with_year <- lead_cod_2_USA_from_2008 %>% 
  group_by(Year, `Cause Name`) %>%
  summarise(Total_Deaths = sum(Deaths, na.rm = TRUE)) 

cause_order = c("All causes","Heart disease","Cancer","Stroke", 
                "CLRD", "Unintentional injuries","Alzheimer's disease", 
                "Diabetes", "Influenza and pneumonia", "Kidney disease","Suicide" )

lead_cod_2_USA_from_2008_with_year$`Cause Name` <- factor(lead_cod_2_USA_from_2008_with_year$`Cause Name`, levels = cause_order)

# Fill = Year
ggplot(lead_cod_2_USA_from_2008_with_year, aes(x = `Cause Name`, y = Total_Deaths, fill = as.factor(Year))) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_brewer(palette = "Set1") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Cause Name", y = "Total Deaths", fill = "Year", 
       title = "Deaths by Cause and Year from 2008-2017 Broken Down By Year")
```

